export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const CHANGE_CATEGORY_NAME = "CHANGE_CATEGORY_NAME";
export const UPDATE_CATEGORY_TITLE_ATTRIBUTE =
  "UPDATE_CATEGORY_TITLE_ATTRIBUTE";
export const UPDATE_CATEGORY_ATTRIBUTE = "UPDATE_CATEGORY_ATTRIBUTE";
export const REMOVE_CATEGORY_ATTRIBUTE = "REMOVE_CATEGORY_ATTRIBUTE";
export const ADD_CATEGORY_ATTRIBUTE = "ADD_CATEGORY_ATTRIBUTE";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
