export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const CHANGE_CATEGORY_NAME = "CHANGE_CATEGORY_NAME";
export const UPDATE_CATEGORY_ATTRIBUTE = "UPDATE_CATEGORY_ATTRIBUTE";
export const REMOVE_CATEGORY_ATTRIBUTE = "REMOVE_CATEGORY_ATTRIBUTE";
export const ADD_CATEGORY_ATTRIBUTE = "ADD_CATEGORY_ATTRIBUTE";
